<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/python_pandas/connecting_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))
df2 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))
df3 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))
s = pd.Series(np.random.rand(10), name='x')

In [3]:
df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)
df

           a         b         c         d
0   0.772625  0.708314  0.226471  0.889358
1   0.114014  0.276900  0.109571  0.315928
2   0.990416  0.291272  0.702782  0.111338
3   0.984562  0.529677  0.858742  0.973573
4   0.266898  0.053493  0.511986  0.580536
5   0.237526  0.644449  0.848661  0.623951
6   0.187950  0.095505  0.698494  0.408051
7   0.200764  0.392488  0.612380  0.532203
8   0.567516  0.932365  0.007857  0.028593
9   0.795759  0.715946  0.939354  0.476380
10  0.057032  0.377213  0.837794  0.043958
11  0.799096  0.020548  0.237662  0.104129
12  0.389961  0.933292  0.838804  0.881429
13  0.348509  0.710023  0.195609  0.717114
14  0.433803  0.021550  0.620227  0.136088
15  0.475742  0.043438  0.857361  0.790742
16  0.799037  0.895155  0.650316  0.919298
17  0.438384  0.850144  0.904285  0.227142
18  0.461381  0.689307  0.671063  0.810481
19  0.903476  0.115924  0.776640  0.911119
20  0.315092  0.436661  0.303330  0.393985
21  0.032338  0.738531  0.180306  0.919116
22  0.219965  0.444295  0.261451  0.905212
23  0.951299  0.109938  0.955105  0.963443
24  0.929306  0.073188  0.405036  0.805698
25  0.729643  0.904527  0.804209  0.390152
26  0.379007  0.071348  0.848918  0.583796
27  0.479032  0.421491  0.023738  0.305948
28  0.443443  0.590620  0.130787  0.133503
29  0.288459  0.494462  0.637297  0.310020

In [4]:
df = pd.concat([df1, df2, df3], axis=0)
df.reset_index()

    index         a         b         c         d
0       0  0.772625  0.708314  0.226471  0.889358
1       1  0.114014  0.276900  0.109571  0.315928
2       2  0.990416  0.291272  0.702782  0.111338
3       3  0.984562  0.529677  0.858742  0.973573
4       4  0.266898  0.053493  0.511986  0.580536
5       5  0.237526  0.644449  0.848661  0.623951
6       6  0.187950  0.095505  0.698494  0.408051
7       7  0.200764  0.392488  0.612380  0.532203
8       8  0.567516  0.932365  0.007857  0.028593
9       9  0.795759  0.715946  0.939354  0.476380
10      0  0.057032  0.377213  0.837794  0.043958
11      1  0.799096  0.020548  0.237662  0.104129
12      2  0.389961  0.933292  0.838804  0.881429
13      3  0.348509  0.710023  0.195609  0.717114
14      4  0.433803  0.021550  0.620227  0.136088
15      5  0.475742  0.043438  0.857361  0.790742
16      6  0.799037  0.895155  0.650316  0.919298
17      7  0.438384  0.850144  0.904285  0.227142
18      8  0.461381  0.689307  0.671063  0.810481
19      9  0.903476  0.115924  0.776640  0.911119
20      0  0.315092  0.436661  0.303330  0.393985
21      1  0.032338  0.738531  0.180306  0.919116
22      2  0.219965  0.444295  0.261451  0.905212
23      3  0.951299  0.109938  0.955105  0.963443
24      4  0.929306  0.073188  0.405036  0.805698
25      5  0.729643  0.904527  0.804209  0.390152
26      6  0.379007  0.071348  0.848918  0.583796
27      7  0.479032  0.421491  0.023738  0.305948
28      8  0.443443  0.590620  0.130787  0.133503
29      9  0.288459  0.494462  0.637297  0.310020

In [5]:
df2 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))
df3 = pd.DataFrame(np.random.rand(10,4), columns=list('efgh'))
df = pd.concat([df2, df3], axis=1)
df

,a,b,c,d,e,f,g,h
0,0.176202,0.638988,0.825373,0.747099,0.671991,0.818689,0.504074,0.079423
1,0.592356,0.933847,0.707307,0.142208,0.656993,0.738221,0.467627,0.906249
2,0.321143,0.088553,0.604080,0.218168,0.049376,0.162397,0.278533,0.226902
3,0.971643,0.855211,0.057130,0.684384,0.326893,0.590789,0.303801,0.993557
4,0.207489,0.226083,0.823066,0.410673,0.855544,0.737583,0.800242,0.302028
5,0.454780,0.759174,0.937215,0.569860,0.587997,0.707559,0.164366,0.366551
6,0.462259,0.578734,0.201601,0.363742,0.349536,0.571090,0.519228,0.122604
7,0.109675,0.645384,0.715202,0.909073,0.238394,0.514347,0.164040,0.132351
8,0.006234,0.576576,0.568899,0.219853,0.866925,0.134055,0.850841,0.733626
9,0.513955,0.586074,0.683112,0.620424,0.776785,0.926627,0.555198,0.352160

In [6]:
df2 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))
df3 = pd.DataFrame(np.random.rand(10,4), columns=list('efgh'))
df = pd.concat([df2, df3], axis=0)
df

,a,b,c,d,e,f,g,h
0,0.058174,0.826777,0.281961,0.817381,NaN,NaN,NaN,NaN
1,0.396633,0.510001,0.337530,0.179111,NaN,NaN,NaN,NaN
2,0.563074,0.371720,0.905348,0.924384,NaN,NaN,NaN,NaN
3,0.398246,0.230001,0.562057,0.266837,NaN,NaN,NaN,NaN
4,0.191882,0.937969,0.570382,0.547203,NaN,NaN,NaN,NaN
5,0.793874,0.634006,0.815914,0.043319,NaN,NaN,NaN,NaN
6,0.052518,0.640685,0.178222,0.411594,NaN,NaN,NaN,NaN
7,0.577298,0.429107,0.615641,0.546783,NaN,NaN,NaN,NaN
8,0.906712,0.407773,0.121758,0.649828,NaN,NaN,NaN,NaN
9,0.348197,0.945707,0.421239,0.329909,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,0.297186,0.181899,0.250907,0.100033
1,NaN,NaN,NaN,NaN,0.800791,0.035005,0.835375,0.655925
2,NaN,NaN,NaN,NaN,0.999265,0.245685,0.181423,0.397502
3,NaN,NaN,NaN,NaN,0.566049,0.970893,0.329630,0.621700
4,NaN,NaN,NaN,NaN,0.664185,0.153492,0.297478,0.708793
5,NaN,NaN,NaN,NaN,0.147583,0.306777,0.404785,0.669558
6,NaN,NaN,NaN,NaN,0.422889,0.261303,0.017050,0.889749
7,NaN,NaN,NaN,NaN,0.797283,0.745141,0.411665,0.589426
8,NaN,NaN,NaN,NaN,0.788307,0.194204,0.420836,0.912229
9,NaN,NaN,NaN,NaN,0.858336,0.609431,0.195804,0.392334

In [7]:
df2 = df1[::2]

In [8]:
df=pd.concat([df2,df3], axis=1, join='outer')
df

,a,b,c,d,e,f,g,h
0,0.772625,0.708314,0.226471,0.889358,0.297186,0.181899,0.250907,0.100033
2,0.990416,0.291272,0.702782,0.111338,0.999265,0.245685,0.181423,0.397502
4,0.266898,0.053493,0.511986,0.580536,0.664185,0.153492,0.297478,0.708793
6,0.187950,0.095505,0.698494,0.408051,0.422889,0.261303,0.017050,0.889749
8,0.567516,0.932365,0.007857,0.028593,0.788307,0.194204,0.420836,0.912229
1,NaN,NaN,NaN,NaN,0.800791,0.035005,0.835375,0.655925
3,NaN,NaN,NaN,NaN,0.566049,0.970893,0.329630,0.621700
5,NaN,NaN,NaN,NaN,0.147583,0.306777,0.404785,0.669558
7,NaN,NaN,NaN,NaN,0.797283,0.745141,0.411665,0.589426
9,NaN,NaN,NaN,NaN,0.858336,0.609431,0.195804,0.392334

In [9]:
df=pd.concat([df2,df3], axis=1, join='inner')
df

,a,b,c,d,e,f,g,h
0,0.772625,0.708314,0.226471,0.889358,0.297186,0.181899,0.250907,0.100033
2,0.990416,0.291272,0.702782,0.111338,0.999265,0.245685,0.181423,0.397502
4,0.266898,0.053493,0.511986,0.580536,0.664185,0.153492,0.297478,0.708793
6,0.187950,0.095505,0.698494,0.408051,0.422889,0.261303,0.017050,0.889749
8,0.567516,0.932365,0.007857,0.028593,0.788307,0.194204,0.420836,0.912229

In [10]:
df = pd.concat([df1,s], axis=1)
df

          a         b         c         d         x
0  0.772625  0.708314  0.226471  0.889358  0.855895
1  0.114014  0.276900  0.109571  0.315928  0.374814
2  0.990416  0.291272  0.702782  0.111338  0.139176
3  0.984562  0.529677  0.858742  0.973573  0.897713
4  0.266898  0.053493  0.511986  0.580536  0.062469
5  0.237526  0.644449  0.848661  0.623951  0.266961
6  0.187950  0.095505  0.698494  0.408051  0.288154
7  0.200764  0.392488  0.612380  0.532203  0.045899
8  0.567516  0.932365  0.007857  0.028593  0.694017
9  0.795759  0.715946  0.939354  0.476380  0.985721

In [11]:
df1 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))
df2 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))
df3 = pd.DataFrame(np.random.rand(10,4), columns=list('abcd'))

In [14]:
ten_pl = pd.read_csv('ten.csv', index_col=0)
plw_pl = pd.read_csv('plw.csv', index_col=0)

ten = ten_pl.copy()
plw = plw_pl.copy()

In [16]:
ten = ten_pl.copy()
plw = plw_pl.copy()
ten.columns = ['Open', 'High', 'Low', 'Close', 'Volume']
plw.columns = ['Open', 'High', 'Low', 'Close', 'Volume']

In [17]:
pd.merge(ten, plw, left_index=True, right_index=True)

,Open_x,High_x,Low_x,Close_x,Volume_x,Open_y,High_y,Low_y,Close_y,Volume_y
Data,,,,,,,,,,
2018-05-11,50.303,60.710,49.253,59.747,208348,127.14,143.27,123.35,141.38,84738
2018-05-14,65.529,72.082,62.927,64.276,249288,144.70,155.14,130.47,139.01,120609
2018-05-15,64.179,64.179,56.162,59.747,97505,140.43,140.43,131.90,137.11,27405
2018-05-16,61.193,61.577,57.829,61.356,35290,137.59,164.14,137.59,160.36,73739
2018-05-17,61.549,61.577,56.855,56.855,24976,163.20,164.14,132.37,134.74,115708
...,...,...,...,...,...,...,...,...,...,...
2019-05-16,138.570,143.580,138.570,141.270,22408,179.40,179.99,176.70,178.05,16618
2019-05-17,141.270,141.270,136.070,137.800,12043,180.76,180.76,176.12,177.67,4544
2019-05-20,137.800,137.800,125.280,125.660,31536,178.05,178.05,166.44,171.86,25942
2019-05-21,125.280,132.790,122.380,126.630,26222,170.31,170.31,165.86,165.86,20515
2019-05-22,124.310,129.520,112.940,126.240,59978,162.57,168.96,156.76,166.44,42026

In [18]:
pd.merge(ten, plw, left_index=True, right_index=True, suffixes=('_ten', '_plw'))

,Open_ten,High_ten,Low_ten,Close_ten,Volume_ten,Open_plw,High_plw,Low_plw,Close_plw,Volume_plw
Data,,,,,,,,,,
2018-05-11,50.303,60.710,49.253,59.747,208348,127.14,143.27,123.35,141.38,84738
2018-05-14,65.529,72.082,62.927,64.276,249288,144.70,155.14,130.47,139.01,120609
2018-05-15,64.179,64.179,56.162,59.747,97505,140.43,140.43,131.90,137.11,27405
2018-05-16,61.193,61.577,57.829,61.356,35290,137.59,164.14,137.59,160.36,73739
2018-05-17,61.549,61.577,56.855,56.855,24976,163.20,164.14,132.37,134.74,115708
...,...,...,...,...,...,...,...,...,...,...
2019-05-16,138.570,143.580,138.570,141.270,22408,179.40,179.99,176.70,178.05,16618
2019-05-17,141.270,141.270,136.070,137.800,12043,180.76,180.76,176.12,177.67,4544
2019-05-20,137.800,137.800,125.280,125.660,31536,178.05,178.05,166.44,171.86,25942
2019-05-21,125.280,132.790,122.380,126.630,26222,170.31,170.31,165.86,165.86,20515
2019-05-22,124.310,129.520,112.940,126.240,59978,162.57,168.96,156.76,166.44,42026

In [19]:
pd.merge(ten, plw, left_index=True, right_index=True, suffixes=('_ten', '_plw'), how='outer')

,Open_ten,High_ten,Low_ten,Close_ten,Volume_ten,Open_plw,High_plw,Low_plw,Close_plw,Volume_plw
Data,,,,,,,,,,
2016-10-19,NaN,NaN,NaN,NaN,NaN,49.056,49.150,44.615,47.443,59332
2016-10-20,NaN,NaN,NaN,NaN,NaN,47.253,47.443,45.602,47.443,6954
2016-10-21,NaN,NaN,NaN,NaN,NaN,46.589,47.443,46.570,47.395,1286
2016-10-24,NaN,NaN,NaN,NaN,NaN,47.443,50.290,47.386,49.758,9612
2016-10-25,NaN,NaN,NaN,NaN,NaN,49.815,49.815,48.392,49.530,8049
...,...,...,...,...,...,...,...,...,...,...
2019-05-16,138.57,143.58,138.57,141.27,22408.0,179.400,179.990,176.700,178.050,16618
2019-05-17,141.27,141.27,136.07,137.80,12043.0,180.760,180.760,176.120,177.670,4544
2019-05-20,137.80,137.80,125.28,125.66,31536.0,178.050,178.050,166.440,171.860,25942
2019-05-21,125.28,132.79,122.38,126.63,26222.0,170.310,170.310,165.860,165.860,20515
2019-05-22,124.31,129.52,112.94,126.24,59978.0,162.570,168.960,156.760,166.440,42026

In [20]:
ten['Change'] = ten['Close'] / ten['Close'].shift(1) - 1
plw['Change'] = plw['Close'] / plw['Close'].shift(1) - 1

In [21]:
ten['Flag'] = ten['Change'] > 0
plw['Flag'] = plw['Change'] > 0

In [22]:
ten['Flag'] = ten['Flag'].apply(int)

In [23]:
ten

               Open     High      Low    Close  Volume    Change  Flag
Data
2018-05-11   50.303   60.710   49.253   59.747  208348       NaN     0
2018-05-14   65.529   72.082   62.927   64.276  249288  0.075803     1
2018-05-15   64.179   64.179   56.162   59.747   97505 -0.070462     0
2018-05-16   61.193   61.577   57.829   61.356   35290  0.026930     1
2018-05-17   61.549   61.577   56.855   56.855   24976 -0.073359     0
...             ...      ...      ...      ...     ...       ...   ...
2019-05-16  138.570  143.580  138.570  141.270   22408  0.033809     1
2019-05-17  141.270  141.270  136.070  137.800   12043 -0.024563     0
2019-05-20  137.800  137.800  125.280  125.660   31536 -0.088099     0
2019-05-21  125.280  132.790  122.380  126.630   26222  0.007719     1
2019-05-22  124.310  129.520  112.940  126.240   59978 -0.003080     0

[256 rows x 7 columns]

In [24]:
correlation_matrix = pd.merge(ten, plw, left_index=True, right_index=True, suffixes=('_ten', '_plw'), how='outer').corr()

In [25]:
correlation_matrix

,Open_ten,High_ten,Low_ten,Close_ten,Volume_ten,Change_ten,Flag_ten,Open_plw,High_plw,Low_plw,Close_plw,Volume_plw,Change_plw,Flag_plw
Open_ten,1.000000,0.989912,0.990607,0.982320,-0.085389,-0.070621,0.012213,0.719328,0.694191,0.734110,0.717749,-0.378040,-0.089226,-0.062660
High_ten,0.989912,1.000000,0.985685,0.990685,-0.015434,0.022356,0.082405,0.706471,0.686294,0.722405,0.710738,-0.356804,-0.062337,-0.040876
Low_ten,0.990607,0.985685,1.000000,0.990167,-0.119875,0.012985,0.072887,0.736203,0.710922,0.758349,0.738936,-0.399797,-0.062896,-0.044055
Close_ten,0.982320,0.990685,0.990167,1.000000,-0.066450,0.096452,0.129387,0.721093,0.701842,0.745714,0.733773,-0.379697,-0.026378,-0.013934
Volume_ten,-0.085389,-0.015434,-0.119875,-0.066450,1.000000,0.163440,0.107270,-0.012467,0.031162,-0.060453,-0.014656,0.387188,0.037524,-0.014155
Change_ten,-0.070621,0.022356,0.012985,0.096452,0.163440,1.000000,0.726642,0.028571,0.054822,0.064630,0.089331,0.043142,0.359765,0.239468
Flag_ten,0.012213,0.082405,0.072887,0.129387,0.107270,0.726642,1.000000,0.055559,0.086657,0.088781,0.109000,0.054832,0.267318,0.268817
Open_plw,0.719328,0.706471,0.736203,0.721093,-0.012467,0.028571,0.055559,1.000000,0.998313,0.998137,0.996952,0.377022,-0.017177,-0.018468
High_plw,0.694191,0.686294,0.710922,0.701842,0.031162,0.054822,0.086657,0.998313,1.000000,0.997407,0.998530,0.402587,0.018633,0.006248
Low_plw,0.734110,0.722405,0.758349,0.745714,-0.060453,0.064630,0.088781,0.998137,0.997407,1.000000,0.998518,0.351442,0.015054,0.004499
Close_plw,0.717749,0.710738,0.738936,0.733773,-0.014656,0.089331,0.109000,0.996952,0.998530,0.998518,1.000000,0.377407,0.046246,0.021890
Volume_plw,-0.378040,-0.356804,-0.399797,-0.379697,0.387188,0.043142,0.054832,0.377022,0.402587,0.351442,0.377407,1.000000,0.046217,0.065959
Change_plw,-0.089226,-0.062337,-0.062896,-0.026378,0.037524,0.359765,0.267318,-0.017177,0.018633,0.015054,0.046246,0.046217,1.000000,0.652554
Flag_plw,-0.062660,-0.040876,-0.044055,-0.013934,-0.014155,0.239468,0.268817,-0.018468,0.006248,0.004499,0.021890,0.065959,0.652554,1.000000