<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/python_pandas/Data_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [4]:
s = pd.Series(['Apple','  Microsoft',np.nan,' Google  ','Anazon'], name='stock')

In [6]:
s = s.str.strip()

In [7]:
s = s.str.upper()
s

0        APPLE
1    MICROSOFT
2          NaN
3       GOOGLE
4       ANAZON
Name: stock, dtype: object

In [8]:
s = s.str.lower()
s

0        apple
1    microsoft
2          NaN
3       google
4       anazon
Name: stock, dtype: object

In [9]:
s = s.str.len()
s

0    5.0
1    9.0
2    NaN
3    6.0
4    6.0
Name: stock, dtype: float64

In [13]:
df = pd.DataFrame(np.random.randn(10, 2), columns=['               ID User', '          Price         '])
df

        ID User  Price
0      0.590046       -0.367391
1      0.307994        0.193926
2     -0.230910        0.233586
3      0.346042        3.819133
4     -0.347616       -0.815873
5     -0.495088        0.213658
6     -0.982369       -0.000468
7     -1.971544        0.923180
8      0.610946        0.524980
9     -0.615640        0.606420

In [14]:
df.columns = df.columns.str.strip()
df

    ID User     Price
0  0.590046 -0.367391
1  0.307994  0.193926
2 -0.230910  0.233586
3  0.346042  3.819133
4 -0.347616 -0.815873
5 -0.495088  0.213658
6 -0.982369 -0.000468
7 -1.971544  0.923180
8  0.610946  0.524980
9 -0.615640  0.606420

In [15]:
df.columns = df.columns.str.replace(' ', '_')
df

    ID_User     Price
0  0.590046 -0.367391
1  0.307994  0.193926
2 -0.230910  0.233586
3  0.346042  3.819133
4 -0.347616 -0.815873
5 -0.495088  0.213658
6 -0.982369 -0.000468
7 -1.971544  0.923180
8  0.610946  0.524980
9 -0.615640  0.606420

In [29]:
s = pd.Series(['#sport#good#time', '#work#out#free#time', '#summer#holiday#hot'], name='hashtag')

In [18]:
s = s.str.split('#')
s

0        [, sport, good, time]
1    [, work, out, free, time]
2     [, summer, holiday, hot]
Name: hashtag, dtype: object

In [19]:
hash1 = s.str.get(1)
hash1

0     sport
1      work
2    summer
Name: hashtag, dtype: object

In [20]:
hash2 = s.str.get(2)
hash2

0       good
1        out
2    holiday
Name: hashtag, dtype: object

In [21]:
hash3 = s.str.get(3)
hash3

0    time
1    free
2     hot
Name: hashtag, dtype: object

In [24]:
df_concat = pd.concat([hash1, hash2, hash3], axis=0, ignore_index=True)
df_concat

0      sport
1       work
2     summer
3       good
4        out
5    holiday
6       time
7       free
8        hot
Name: hashtag, dtype: object

In [27]:
string = df_concat.str.cat(sep=' ')
string

'sport work summer good out holiday time free hot'

In [28]:
df_concat = pd.concat([hash1, hash2, hash3], axis=1, ignore_index=True)
df_concat

        0        1     2
0   sport     good  time
1    work      out  free
2  summer  holiday   hot

In [31]:
split_2 = s.str.split('#', expand=True)
split_2

  0       1        2     3     4
0     sport     good  time  None
1      work      out  free  time
2    summer  holiday   hot  None

In [33]:
split_2 = split_2.drop(0, axis=1)

In [34]:
split_2

        1        2     3     4
0   sport     good  time  None
1    work      out  free  time
2  summer  holiday   hot  None

In [36]:
s.str.replace('#', ' ')

0        sport good time
1     work out free time
2     summer holiday hot
Name: hashtag, dtype: object

In [37]:
s.str.replace('#', '_')

0       _sport_good_time
1    _work_out_free_time
2    _summer_holiday_hot
Name: hashtag, dtype: object

In [38]:
s.str.replace('#', '')

0       sportgoodtime
1     workoutfreetime
2    summerholidayhot
Name: hashtag, dtype: object

In [39]:
string = 'workout summer good free holiday time time hot'

In [40]:
split = string.split(' ')
split

['workout', 'summer', 'good', 'free', 'holiday', 'time', 'time', 'hot']

In [42]:
s = pd.Series(split)
s

0    workout
1     summer
2       good
3       free
4    holiday
5       time
6       time
7        hot
dtype: object

In [43]:
s.str.contains(r'[0-9]')

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [44]:
s.str.contains(r'[a-z]')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
dtype: bool

In [45]:
s.str.contains(r'[rg]')

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7    False
dtype: bool

In [47]:
s[s.str.contains(r'[rg]')]

0    workout
1     summer
2       good
3       free
dtype: object