<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/python_pandas/otwieranie_plikow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('apple.csv', index_col=0)
df

             Otwarcie  Najwyzszy  Najnizszy  Zamkniecie     Wolumen
Data
1984-09-07    0.41583    0.42087    0.41079     0.41583  23669718.0
1984-09-10    0.41583    0.41708    0.40581     0.41334  18371562.0
1984-09-11    0.41708    0.42839    0.41708     0.42087  43321235.0
1984-09-12    0.42087    0.42337    0.40828     0.40828  37844792.0
1984-09-13    0.43093    0.43215    0.43093     0.43093  58941865.0
...               ...        ...        ...         ...         ...
2019-05-06  204.29000  208.84000  203.50000   208.48000  32443113.0
2019-05-07  205.88000  207.41800  200.82500   202.86000  38763698.0
2019-05-08  201.90000  205.34000  201.75000   202.90000  26339504.0
2019-05-09  200.40000  201.68000  196.66000   200.72000  34908607.0
2019-05-10  197.41900  198.85000  192.77000   197.18000  41208712.0

[8738 rows x 5 columns]

In [ ]:
df = pd.read_csv('apple.csv', index_col=0, skiprows=10)
df

              0.42463    0.42839  0.42463.1  0.42463.2    18810964
1984-09-20
1984-09-21    0.42463    0.43719    0.41583    0.42087  28381993.0
1984-09-24    0.42087    0.42337    0.41708    0.41708  22459810.0
1984-09-25    0.41583    0.41583    0.40828    0.40828  47415847.0
1984-09-26    0.40828    0.42712    0.40330    0.40330  31546888.0
1984-09-27    0.40330    0.40581    0.40330    0.40330  30114092.0
...               ...        ...        ...        ...         ...
2019-05-06  204.29000  208.84000  203.50000  208.48000  32443113.0
2019-05-07  205.88000  207.41800  200.82500  202.86000  38763698.0
2019-05-08  201.90000  205.34000  201.75000  202.90000  26339504.0
2019-05-09  200.40000  201.68000  196.66000  200.72000  34908607.0
2019-05-10  197.41900  198.85000  192.77000  197.18000  41208712.0

[8728 rows x 5 columns]

In [ ]:
df = pd.read_csv('apple.csv', index_col=0, nrows=10)
df

            Otwarcie  Najwyzszy  Najnizszy  Zamkniecie   Wolumen
Data
1984-09-07   0.41583    0.42087    0.41079     0.41583  23669718
1984-09-10   0.41583    0.41708    0.40581     0.41334  18371562
1984-09-11   0.41708    0.42839    0.41708     0.42087  43321235
1984-09-12   0.42087    0.42337    0.40828     0.40828  37844792
1984-09-13   0.43093    0.43215    0.43093     0.43093  58941865
1984-09-14   0.43215    0.44723    0.43215     0.43719  70181304
1984-09-17   0.44849    0.45477    0.44849     0.44849  54796306
1984-09-18   0.44849    0.45228    0.43215     0.43215  27662429
1984-09-19   0.43215    0.43719    0.42337     0.42337  30215978
1984-09-20   0.42463    0.42839    0.42463     0.42463  18810964

In [ ]:
df = pd.read_csv('apple.tsv', sep='\t', index_col=0)
df

            Otwarcie  Najwyzszy  Najnizszy  Zamkniecie     Wolumen
Data
1984-09-07      0.42       0.42       0.41        0.42  23669718.0
1984-09-10      0.42       0.42       0.41        0.41  18371562.0
1984-09-11      0.42       0.43       0.42        0.42  43321235.0
1984-09-12      0.42       0.42       0.41        0.41  37844792.0
1984-09-13      0.43       0.43       0.43        0.43  58941865.0
...              ...        ...        ...         ...         ...
2019-05-06    204.29     208.84     203.50      208.48  32443113.0
2019-05-07    205.88     207.42     200.82      202.86  38763698.0
2019-05-08    201.90     205.34     201.75      202.90  26339504.0
2019-05-09    200.40     201.68     196.66      200.72  34908607.0
2019-05-10    197.42     198.85     192.77      197.18  41208712.0

[8738 rows x 5 columns]

In [3]:
df = pd.read_excel('companies.xlsx')
df

           Data  Otwarcie  Najwyzszy  Najnizszy  Zamkniecie   Wolumen
0    2010-06-28     17.00     17.000     17.000       17.00         ?
1    2010-06-29     19.00     25.000     17.540       23.89  18783276
2    2010-06-30     25.79     30.420     23.300       23.83  17194394
3    2010-07-01     25.00     25.920     20.270       21.96   8229863
4    2010-07-02     23.00     23.100     18.710       19.20   5141807
...         ...       ...        ...        ...         ...       ...
2227 2019-05-06    250.02    258.350    248.500      255.34  10833943
2228 2019-05-07    256.80    257.210    245.100      247.06  10131408
2229 2019-05-08    246.94    250.599    244.200      244.84   6176440
2230 2019-05-09    242.00    243.680    236.943      241.98   6711382
2231 2019-05-10    239.75    241.990    236.020      239.52   7008336

[2232 rows x 6 columns]

In [5]:
df = pd.read_excel('companies.xlsx', na_values='?', index_col=0)
df

            Otwarcie  Najwyzszy  Najnizszy  Zamkniecie     Wolumen
Data
2010-06-28     17.00     17.000     17.000       17.00         NaN
2010-06-29     19.00     25.000     17.540       23.89  18783276.0
2010-06-30     25.79     30.420     23.300       23.83  17194394.0
2010-07-01     25.00     25.920     20.270       21.96   8229863.0
2010-07-02     23.00     23.100     18.710       19.20   5141807.0
...              ...        ...        ...         ...         ...
2019-05-06    250.02    258.350    248.500      255.34  10833943.0
2019-05-07    256.80    257.210    245.100      247.06  10131408.0
2019-05-08    246.94    250.599    244.200      244.84   6176440.0
2019-05-09    242.00    243.680    236.943      241.98   6711382.0
2019-05-10    239.75    241.990    236.020      239.52   7008336.0

[2232 rows x 5 columns]

In [10]:
df = pd.read_excel('companies.xlsx', sheet_name='microsoft', index_col=0)
df

             Otwarcie  Najwyzszy  Najnizszy  Zamkniecie       Wolumen
Data
1986-03-13    0.06545    0.07337    0.06545     0.07337  1.408064e+09
1986-03-14    0.07337    0.07337    0.07337     0.07337  4.205405e+08
1986-03-17    0.07337    0.07337    0.07337     0.07337  1.817364e+08
1986-03-18    0.07337    0.07337    0.07337     0.07337  9.247961e+07
1986-03-19    0.07337    0.07337    0.07337     0.07337  6.536064e+07
...               ...        ...        ...         ...           ...
2019-05-06  126.39000  128.56000  126.11000   128.15000  2.423946e+07
2019-05-07  126.46000  127.18000  124.22000   125.52000  3.601766e+07
2019-05-08  125.44000  126.37000  124.75000   125.51000  2.841900e+07
2019-05-09  124.29000  125.79000  123.57000   125.50000  2.723584e+07
2019-05-10  124.91000  127.93000  123.82000   127.13000  3.091508e+07

[8357 rows x 5 columns]

Available sheet names in 'companies.xlsx': ['tesla', 'microsoft', 'google']

In [19]:
df = pd.read_html('small.html', header=0, index_col=0)[0]
df = df.iloc[1:]
df

            Otwarcie  Najwyzszy  Najnizszy  Zamkniecie     Wolumen
2010-06-28     17.00      17.00      17.00       17.00         NaN
2010-06-29     19.00      25.00      17.54       23.89  18783276.0
2010-06-30     25.79      30.42      23.30       23.83  17194394.0
2010-07-01     25.00      25.92      20.27       21.96   8229863.0
2010-07-02     23.00      23.10      18.71       19.20   5141807.0
2010-07-06     20.00      20.00      15.83       16.11   6879296.0
2010-07-07     16.40      16.63      14.98       15.80   6924914.0
2010-07-08     16.14      17.52      15.57       17.46   7719539.0
2010-07-09     17.58      17.90      16.55       17.40   4058606.0
2010-07-12     17.95      18.07      17.00       17.05   2203570.0

HTTPError: HTTP Error 403: Forbidden

In [21]:
df= pd.read_sas('stocks.sas7bdat')
df

              Stock     Date   Open   High    Low  Close      Volume
0    b'ABC Company'  21154.0  89.15  89.92  81.56  82.20   5976252.0
1    b'ABC Company'  21124.0  81.85  89.94  80.64  88.90   5556471.0
2    b'ABC Company'  21095.0  80.22  84.60  78.70  81.88   7019666.0
3    b'ABC Company'  21063.0  80.16  82.11  76.93  80.22   5772280.0
4    b'ABC Company'  21032.0  83.00  84.20  79.87  80.62   4801386.0
..              ...      ...    ...    ...    ...    ...         ...
187      b'XYZ Inc'  18383.0  80.94  85.44  71.25  71.44  58246800.0
188      b'XYZ Inc'  18353.0  77.50  85.06  71.31  80.81  76032038.0
189      b'XYZ Inc'  18323.0  89.81  91.37  74.00  78.06  79953345.0
190      b'XYZ Inc'  18295.0  82.50  95.62  82.19  89.69  74033663.0
191      b'XYZ Inc'  18264.0  70.69  82.87  70.50  81.00  70181140.0

[192 rows x 7 columns]