<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/python_pandas/queryselection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.rand(10,5),
                  columns=['A','B','C','D','E'])
df.query('(A<B)')

          A         B         C         D         E
0  0.215406  0.419293  0.875170  0.625704  0.142241
3  0.004775  0.441153  0.822764  0.794291  0.512539
4  0.452748  0.858952  0.993536  0.038112  0.239961
7  0.427705  0.811984  0.097170  0.044932  0.294017
9  0.079426  0.331420  0.250196  0.829887  0.114207

In [3]:
df.query('(A<B) & (B<C)')

          A         B         C         D         E
0  0.215406  0.419293  0.875170  0.625704  0.142241
3  0.004775  0.441153  0.822764  0.794291  0.512539
4  0.452748  0.858952  0.993536  0.038112  0.239961

In [4]:
df.query('(A<B) | (B<C)')

          A         B         C         D         E
0  0.215406  0.419293  0.875170  0.625704  0.142241
1  0.931033  0.357528  0.976320  0.235923  0.176379
2  0.688145  0.560918  0.797191  0.909122  0.838246
3  0.004775  0.441153  0.822764  0.794291  0.512539
4  0.452748  0.858952  0.993536  0.038112  0.239961
5  0.380849  0.292878  0.494541  0.486012  0.428219
6  0.357555  0.103206  0.349875  0.292452  0.745862
7  0.427705  0.811984  0.097170  0.044932  0.294017
9  0.079426  0.331420  0.250196  0.829887  0.114207

In [11]:
df = df.round(1)

df.query('C ==[0.5, 0.3]')

     A    B    C    D    E
5  0.4  0.3  0.5  0.5  0.4
6  0.4  0.1  0.3  0.3  0.7
9  0.1  0.3  0.3  0.8  0.1

In [12]:
df.query('C !=0.5')

     A    B    C    D    E
0  0.2  0.4  0.9  0.6  0.1
1  0.9  0.4  1.0  0.2  0.2
2  0.7  0.6  0.8  0.9  0.8
3  0.0  0.4  0.8  0.8  0.5
4  0.5  0.9  1.0  0.0  0.2
6  0.4  0.1  0.3  0.3  0.7
7  0.4  0.8  0.1  0.0  0.3
8  0.9  0.4  0.2  0.7  0.8
9  0.1  0.3  0.3  0.8  0.1

In [14]:
df.query('[0.5, 0.8] in C')

     A    B    C    D    E
2  0.7  0.6  0.8  0.9  0.8
3  0.0  0.4  0.8  0.8  0.5
5  0.4  0.3  0.5  0.5  0.4

In [16]:
idx = pd.Index(['8637', '5667', '0964536', '4356'])
df = pd.DataFrame(np.random.randn(4,5), index=idx,
                  columns=list('abcde'))
df

                a         b         c         d         e
8637    -1.126778 -0.725304 -0.134072  0.247792 -0.686105
5667    -1.486384  0.200158 -2.207639  0.272302 -0.923645
0964536  1.634584  0.733384 -1.535778  0.263752  1.308614
4356    -0.671591 -0.766120  1.511609 -1.010585  0.042146