<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/python_pandas/Untitled34.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.randn(10,4),
                  columns=['one', 'two', 'three', 'four'])

In [3]:
for row in df.values:
  i = np.random.choice([0,1,2,3])
  row[i] = np.nan
df

        one       two     three      four
0  0.248245       NaN -0.338442  0.089686
1       NaN  1.285680 -0.563224 -0.301604
2 -0.707514  0.110899  0.516967       NaN
3  0.466105 -0.441666 -0.413935       NaN
4  0.778842       NaN  1.134165  1.866882
5 -0.081605       NaN -1.537400  0.498250
6  1.043232  0.303182  0.742781       NaN
7  0.980978 -0.377784 -0.116559       NaN
8       NaN -0.080065 -0.130775 -0.037902
9       NaN -0.259452 -0.979211  1.087565

In [4]:
for row in df.values:
  switch = np.random.choice([0,1])
  if switch == 1:
    i = np.random.choice([0,1,2,3])
    row[i] = np.nan
df

        one       two     three      four
0       NaN       NaN -0.338442  0.089686
1       NaN  1.285680       NaN -0.301604
2 -0.707514  0.110899  0.516967       NaN
3       NaN -0.441666 -0.413935       NaN
4  0.778842       NaN       NaN  1.866882
5 -0.081605       NaN -1.537400       NaN
6  1.043232  0.303182  0.742781       NaN
7  0.980978 -0.377784 -0.116559       NaN
8       NaN -0.080065       NaN -0.037902
9       NaN -0.259452 -0.979211       NaN

In [5]:
df.isnull()

     one    two  three   four
0   True   True  False  False
1   True  False   True  False
2  False  False  False   True
3   True  False  False   True
4  False   True   True  False
5  False   True  False   True
6  False  False  False   True
7  False  False  False   True
8   True  False   True  False
9   True  False  False   True

In [6]:
df['one'].isnull()

0     True
1     True
2    False
3     True
4    False
5    False
6    False
7    False
8     True
9     True
Name: one, dtype: bool

In [7]:
df[df['one'].isnull()]

   one       two     three      four
0  NaN       NaN -0.338442  0.089686
1  NaN  1.285680       NaN -0.301604
3  NaN -0.441666 -0.413935       NaN
8  NaN -0.080065       NaN -0.037902
9  NaN -0.259452 -0.979211       NaN

In [8]:
df[~df['one'].isnull()]

        one       two     three      four
2 -0.707514  0.110899  0.516967       NaN
4  0.778842       NaN       NaN  1.866882
5 -0.081605       NaN -1.537400       NaN
6  1.043232  0.303182  0.742781       NaN
7  0.980978 -0.377784 -0.116559       NaN

In [9]:
df.notnull()

     one    two  three   four
0  False  False   True   True
1  False   True  False   True
2   True   True   True  False
3  False   True   True  False
4   True  False  False   True
5   True  False   True  False
6   True   True   True  False
7   True   True   True  False
8  False   True  False   True
9  False   True   True  False

In [10]:
df[df.notnull()]

        one       two     three      four
0       NaN       NaN -0.338442  0.089686
1       NaN  1.285680       NaN -0.301604
2 -0.707514  0.110899  0.516967       NaN
3       NaN -0.441666 -0.413935       NaN
4  0.778842       NaN       NaN  1.866882
5 -0.081605       NaN -1.537400       NaN
6  1.043232  0.303182  0.742781       NaN
7  0.980978 -0.377784 -0.116559       NaN
8       NaN -0.080065       NaN -0.037902
9       NaN -0.259452 -0.979211       NaN

In [11]:
df['one'].notnull()

0    False
1    False
2     True
3    False
4     True
5     True
6     True
7     True
8    False
9    False
Name: one, dtype: bool

In [12]:
df[df['one'].notnull()]

        one       two     three      four
2 -0.707514  0.110899  0.516967       NaN
4  0.778842       NaN       NaN  1.866882
5 -0.081605       NaN -1.537400       NaN
6  1.043232  0.303182  0.742781       NaN
7  0.980978 -0.377784 -0.116559       NaN

In [13]:
df['five'] = np.nan

In [14]:
df

        one       two     three      four  five
0       NaN       NaN -0.338442  0.089686   NaN
1       NaN  1.285680       NaN -0.301604   NaN
2 -0.707514  0.110899  0.516967       NaN   NaN
3       NaN -0.441666 -0.413935       NaN   NaN
4  0.778842       NaN       NaN  1.866882   NaN
5 -0.081605       NaN -1.537400       NaN   NaN
6  1.043232  0.303182  0.742781       NaN   NaN
7  0.980978 -0.377784 -0.116559       NaN   NaN
8       NaN -0.080065       NaN -0.037902   NaN
9       NaN -0.259452 -0.979211       NaN   NaN

In [15]:
del df['five']
df

        one       two     three      four
0       NaN       NaN -0.338442  0.089686
1       NaN  1.285680       NaN -0.301604
2 -0.707514  0.110899  0.516967       NaN
3       NaN -0.441666 -0.413935       NaN
4  0.778842       NaN       NaN  1.866882
5 -0.081605       NaN -1.537400       NaN
6  1.043232  0.303182  0.742781       NaN
7  0.980978 -0.377784 -0.116559       NaN
8       NaN -0.080065       NaN -0.037902
9       NaN -0.259452 -0.979211       NaN

In [27]:
df = pd.DataFrame(np.random.randn(10,4),
                  columns=['one', 'two', 'three', 'four'])
for row in df.values:
  switch = np.random.choice([0,1])
  if switch == 1:
    i = np.random.choice([0,1,2,3])
    row[i] = np.nan
df

        one       two     three      four
0 -0.618135 -0.554616       NaN  0.464791
1  0.399430  1.144015  0.080957       NaN
2  0.856810 -0.066959  0.239348  0.088649
3  1.613613  0.619635       NaN -1.327010
4  0.857235  0.107487  0.569000       NaN
5 -0.429562  0.785749 -0.223176 -1.406147
6  0.932595 -1.162089       NaN  0.965347
7  0.349654  0.600563  0.205895       NaN
8 -0.612992 -0.089858  0.225108 -0.847757
9  0.872611 -1.320937 -0.798648  0.637422

In [21]:
df = df.fillna('bo acces')
df

        one       two     three      four
0 -0.196422  1.923899 -0.314875  1.077459
1  0.641956 -0.808135  0.192584  bo acces
2  bo acces  0.724199 -0.352732  1.241128
3 -0.514621 -0.537688  -0.45472 -0.076933
4  bo acces -0.488332  0.480238  0.749775
5  1.592758  0.748402 -0.399767   1.15595
6 -0.133403 -0.818556  bo acces  0.203512
7  bo acces  1.706446   1.05507 -1.442381
8  0.840154  0.000244  0.331142  0.723677
9  0.383963  bo acces -0.660144 -1.153054

In [24]:
df['one'] = df['one'].fillna(0)
df

        one       two     three      four
0  0.000000  0.948615 -0.972174 -0.556603
1  0.573983  0.630905 -2.436859  0.535108
2  0.213092  1.694695 -0.885113 -0.615097
3 -1.602332 -0.256351       NaN  0.969817
4 -1.788233  0.483516 -0.150322 -0.159903
5  0.183007 -0.841422       NaN  0.441269
6 -0.680174  1.074488 -0.019628       NaN
7  0.000000  0.252838  0.589317  0.282692
8 -1.373004 -0.775238       NaN -0.767491
9 -0.264283 -1.185826 -0.530108 -0.139339

In [26]:
df = df.fillna(df.mean())
df

        one       two     three      four
0  0.000000  0.948615 -0.972174 -0.556603
1  0.573983  0.630905 -2.436859  0.535108
2  0.213092  1.694695 -0.885113 -0.615097
3 -1.602332 -0.256351 -0.629270  0.969817
4 -1.788233  0.483516 -0.150322 -0.159903
5  0.183007 -0.841422 -0.629270  0.441269
6 -0.680174  1.074488 -0.019628 -0.001061
7  0.000000  0.252838  0.589317  0.282692
8 -1.373004 -0.775238 -0.629270 -0.767491
9 -0.264283 -1.185826 -0.530108 -0.139339

In [28]:
df['four'] = df['four'].fillna(df['four'].mean())
df

        one       two     three      four
0 -0.618135 -0.554616       NaN  0.464791
1  0.399430  1.144015  0.080957 -0.203529
2  0.856810 -0.066959  0.239348  0.088649
3  1.613613  0.619635       NaN -1.327010
4  0.857235  0.107487  0.569000 -0.203529
5 -0.429562  0.785749 -0.223176 -1.406147
6  0.932595 -1.162089       NaN  0.965347
7  0.349654  0.600563  0.205895 -0.203529
8 -0.612992 -0.089858  0.225108 -0.847757
9  0.872611 -1.320937 -0.798648  0.637422

In [29]:
df = pd.DataFrame(np.random.randn(10,4),
                  columns=['one', 'two', 'three', 'four'])
for row in df.values:
  switch = np.random.choice([0,1])
  if switch == 1:
    i = np.random.choice([0,1,2,3])
    row[i] = np.nan
df

        one       two     three      four
0  0.175329       NaN  0.357859  2.683301
1 -1.719792  0.196895 -0.252131       NaN
2  0.126372 -0.733422 -0.246933 -0.828832
3       NaN  0.169418 -0.738893 -0.783680
4  0.782608 -0.576312       NaN  0.526752
5       NaN -0.352467  0.177681  1.312760
6 -1.129236 -0.268403  0.539116       NaN
7 -1.003973  0.053851  0.134962 -0.314396
8  0.124741  0.211228  0.354304  0.779019
9  1.296205 -3.986232  0.476824  0.369144

In [30]:
df.describe()

            one       two     three      four
count  8.000000  9.000000  9.000000  8.000000
mean  -0.168468 -0.587272  0.089199  0.468008
std    1.025995  1.321333  0.421350  1.170577
min   -1.719792 -3.986232 -0.738893 -0.828832
25%   -1.035289 -0.576312 -0.246933 -0.431717
50%    0.125556 -0.268403  0.177681  0.447948
75%    0.327149  0.169418  0.357859  0.912454
max    1.296205  0.211228  0.539116  2.683301

In [33]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]