<a href="https://colab.research.google.com/github/guzik1234/DataScienceCwiczenia/blob/main/Plotly/Interaktywne_wykresy48.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install chart_studio -q
!pip install --upgrade plotly -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 84.2 MB/s eta 0:00:00

In [2]:
import plotly
print(plotly.__version__)

7.1.0

In [3]:
import plotly.express as px
data = px.data.iris()
data.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [4]:
px.scatter(data_frame = data,
           x='sepal_length',
           y='sepal_width',
           color='species',
           marginal_x='violin',
           marginal_y='box',
           symbol='species',
           title='Iris Dataset',
           trendline='ols'
           )

In [5]:
df = px.data.tips()
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
df.describe(include='object')

         sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [8]:
px.scatter(data_frame=df,
           x='total_bill',
           y='tip',
           facet_col='day',
           category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun']},
           trendline='ols',
           color='smoker')

In [9]:
px.scatter(data_frame=df,
           x='total_bill',
           y='tip',
           facet_row='time',
           category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun']},
           trendline='ols',
           color='smoker')

In [10]:
px.scatter_matrix(data_frame=data, dimensions=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'],
                  color='species',
                  title='Scatter Matrix Plot')

In [11]:
px.parallel_coordinates(data_frame=data, color='species_id')

In [12]:
data = px.data.tips()

In [13]:
px.parallel_categories(data, color='size')

In [14]:
df = px.data.gapminder()
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [15]:
df.describe()

             year      lifeExp           pop      gdpPercap      iso_num
count  1704.00000  1704.000000  1.704000e+03    1704.000000  1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081   425.880282
std      17.26533    12.917107  1.061579e+08    9857.454543   248.305709
min    1952.00000    23.599000  6.001100e+04     241.165876     4.000000
25%    1965.75000    48.198000  2.793664e+06    1202.060309   208.000000
50%    1979.50000    60.712500  7.023596e+06    3531.846989   410.000000
75%    1993.25000    70.845500  1.958522e+07    9325.462346   638.000000
max    2007.00000    82.603000  1.318683e+09  113523.132900   894.000000

In [16]:
df.describe(include='object')

            country continent iso_alpha
count          1704      1704      1704
unique          142         5       141
top     Afghanistan    Africa       KOR
freq             12       624        24

In [17]:
px.scatter(df.query('year==2007'), x='gdpPercap', y='lifeExp', size='pop', color='continent', log_x=True,
           hover_name='country', size_max=60)

In [18]:
px.scatter(df, x='gdpPercap', y='lifeExp', size='pop', color='continent', log_x=True,
           hover_name='country', size_max=60, animation_frame='year', range_y=[25, 90])

In [19]:
px.scatter(df, x='gdpPercap', y='lifeExp', size='pop', color='continent', log_x=True,
           hover_name='country', size_max=60, animation_frame='year', range_y=[25, 90], facet_col='continent')

In [20]:
px.line(df.query("country=='Poland'"), x='year', y='pop')

In [21]:
px.line(df.query("continent=='Europe'"), x='year', y='pop', color='country')

In [22]:
for tempalte in ['plotly', 'plotly_white', 'plotly_dark', 'ggplot2', 'seaborn']:

  fig = px.scatter(df.query('year==2007'), x='gdpPercap', y='lifeExp', size='pop', color='continent', log_x=True,
           height=400, size_max=60, title=f'Template {tempalte}', template=tempalte)
  fig.show()

In [23]:
import plotly.io as pio

pio.templates.default = 'plotly_dark'
df = px.data.iris()

fig = px.scatter(df, x='sepal_length', y='sepal_width')
fig.show()

In [24]:
!pip install -q chart_studio
!pip install --upgrade plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (7.1.0)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly) (26.3)

In [25]:
import plotly.express as px
import pandas as pd
import yfinance as yf

def fetch_financial_data(company='AMZN'):
    """
    This function fetches stock market quotations using yfinance.
    """
    # Pobieramy dane historyczne dla wybranej spółki
    df = yf.download(company)
    return df

df = fetch_financial_data()
df.head()
df = df.reset_index()
df.head()

/tmp/ipykernel_1506/32726475.py:10: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(company)
[*********************100%***********************]  1 of 1 completed

Price        Date       Close        High         Low        Open    Volume
Ticker                   AMZN        AMZN        AMZN        AMZN      AMZN
0      2026-09-01  254.919998  255.820007  251.929993  254.830002  31700100
1      2026-09-02  254.979996  256.239990  253.399994  254.259995  24013300
2      2026-09-03  258.899994  259.500000  256.000000  256.200012  26891500
3      2026-09-04  258.510010  261.119995  255.289993  259.070007  30749900
4      2026-09-08  256.970001  257.989990  254.750000  256.679993  29398000

In [26]:
df.head()

Price        Date       Close        High         Low        Open    Volume
Ticker                   AMZN        AMZN        AMZN        AMZN      AMZN
0      2026-09-01  254.919998  255.820007  251.929993  254.830002  31700100
1      2026-09-02  254.979996  256.239990  253.399994  254.259995  24013300
2      2026-09-03  258.899994  259.500000  256.000000  256.200012  26891500
3      2026-09-04  258.510010  261.119995  255.289993  259.070007  30749900
4      2026-09-08  256.970001  257.989990  254.750000  256.679993  29398000

In [27]:
df = df[df['Date']>='2019-01-01']
df.describe()

Price,Date,Close,High,Low,Open,Volume
Ticker,,AMZN,AMZN,AMZN,AMZN,AMZN
count,21,21.000000,21.000000,21.000000,21.000000,2.100000e+01
mean,2026-09-15 17:08:34.285714176,252.470952,254.551426,250.095237,252.138334,3.424314e+07
min,2026-09-01 00:00:00,245.960007,247.770004,244.300003,246.020004,2.401330e+07
25%,2026-09-09 00:00:00,249.270004,252.440002,247.179993,248.559998,3.043880e+07
50%,2026-09-16 00:00:00,252.399994,254.690002,250.649994,253.000000,3.305550e+07
75%,2026-09-23 00:00:00,254.979996,257.589996,253.399994,254.830002,3.627540e+07
max,2026-09-30 00:00:00,258.899994,261.119995,256.000000,259.070007,5.227470e+07
std,NaN,4.163493,3.800315,3.763220,3.827324,6.970701e+06

In [28]:
df.columns = [col[0] if isinstance(col, tuple) else col for col in df.columns]

# Rysujemy wykres na pełnych nazwach
px.area(df, x='Date', y='Close', log_y=True, title='Wykres amazon')

In [29]:
from seaborn import load_dataset
import pandas as pd

df= load_dataset('flights')
df.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [30]:
df.describe()

              year  passengers
count   144.000000  144.000000
mean   1954.500000  280.298611
std       3.464102  119.966317
min    1949.000000  104.000000
25%    1951.750000  180.000000
50%    1954.500000  265.500000
75%    1957.250000  360.500000
max    1960.000000  622.000000

In [31]:
px.bar(df, x='year', y='passengers', title='liczba posazerow podzial na lata')

In [32]:
px.bar(df, x='year', y='passengers', title='liczba posazerow podzial na lata', color='month')

In [33]:
px.bar(df, x='month', y='passengers', title='liczba posazerow podzial na lata', color='year')

In [34]:
px.bar(df, y='month', x='passengers', title='liczba posazerow podzial na lata', color='year',
       orientation='h', category_orders={'month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']})

In [35]:
df.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [36]:
px.bar(df.query('year in [1958, 1959, 1960]'), x='month', y='passengers', color='year')

In [37]:
import plotly.express as px
import pandas as pd

# Przygotowujemy dane jako ramkę DataFrame
data = [
    dict(Task='Projekt A', Start="2019-01-01", Finish="2019-06-01"),
    dict(Task='Projekt B', Start="2019-03-01", Finish="2019-07-01"),
    dict(Task='Projekt C', Start="2019-02-01", Finish="2019-05-01"),
    dict(Task='Projekt D', Start="2019-04-01", Finish="2019-10-01"),
]
df_gantt = pd.DataFrame(data)

# Tworzymy wykres Gantta przy użyciu px.timeline
fig = px.timeline(df_gantt, x_start="Start", x_end="Finish", y="Task")
fig.update_yaxes(autorange="reversed")  # Odwracamy oś Y, aby pierwsze zadanie było na górze
fig.show()

In [38]:
import plotly.express as px
import pandas as pd

# Przygotowujemy dane jako ramkę DataFrame
data = [
    dict(Task='Projekt A', Start="2019-01-01", Finish="2019-06-01", Complete=10),
    dict(Task='Projekt B', Start="2019-03-01", Finish="2019-07-01", Complete=50),
    dict(Task='Projekt C', Start="2019-02-01", Finish="2019-05-01", Complete=100),
    dict(Task='Projekt D', Start="2019-04-01", Finish="2019-10-01", Complete=70),
]
df_gantt = pd.DataFrame(data)

# Tworzymy wykres Gantta przy użyciu px.timeline bez błędnych parametrów
fig = px.timeline(
    df_gantt,
    x_start="Start",
    x_end="Finish",
    y="Task",
    color="Complete",
    color_continuous_scale=["#eb4034", "#34eb89"]
)

# Ewentualna konfiguracja paska kolorów (colorbar) po utworzeniu wykresu
fig.update_layout(coloraxis_showscale=True)

fig.update_yaxes(autorange="reversed")  # Odwracamy oś Y, aby pierwsze zadanie było na górze
fig.show()

In [39]:
df = load_dataset('diamonds')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [40]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [41]:
df = df.cut.value_counts()
df = df.reset_index()

In [42]:
import plotly.graph_objects as go
from seaborn import load_dataset

# Re-load and process the diamonds dataset
df = load_dataset('diamonds')
df = df.cut.value_counts()
df = df.reset_index()

fig = go.Figure(data=[go.Pie(labels=df['cut'], values=df['count'])])
fig.show()

In [43]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Pie(labels=df['cut'], values=df['count'], hole=0.4)])
fig.show()

In [44]:
fig = go.Figure(data=[go.Table(header=dict(values=['USER ID', 'Amount'],
                                           fill_color='lightblue',
                                           line_color='grey'),
                               cells=dict(values=[['010', '019', '013', '031'], [100,150,80,120]],
                                          fill_color='lightgreen'))],
                layout=go.Layout(width=500, height=300))
fig.show()

In [45]:
df = load_dataset('flights')
df.head(3)

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132

In [46]:
df = df[:20]
df.describe()

              year  passengers
count    20.000000   20.000000
mean   1949.400000  132.550000
std       0.502625   17.839858
min    1949.000000  104.000000
25%    1949.000000  118.750000
50%    1949.000000  130.500000
75%    1950.000000  142.750000
max    1950.000000  170.000000

In [47]:
data = [go.Table(header=dict(values=df.columns),
                 cells=dict(values=[df.year.tolist(), df.month.tolist(), df.passengers.tolist()]))]

fig = go.Figure(data=data)
fig.show()

In [48]:
data = [go.Sankey(node=dict(label=['Nonchurn_2018', 'Churn 2018', 'Nonchurn_2019', 'Churn_2019']),
                  link=dict(source=[0,0,1,1],
                            target=[2,3,2,3],
                            value=[65,12,18,5]))]
fig = go.Figure(data=data)
fig.show()

In [49]:
data = [go.Sankey(node=dict(label=['Nonchurn_2018', 'Churn 2018', 'Nonchurn_2019', 'Churn_2019', 'Nonchurn_2020', 'Churn2020']),
                  link=dict(source=[0,0,1,1,2,3],
                            target=[2,3,2,3,4,5],
                            value=[65,10,5,20,70,30]))]
fig = go.Figure(data=data)
fig.show()

In [50]:
from seaborn import load_dataset
import plotly.express as px
import pandas as pd

df = load_dataset('diamonds')
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [51]:
px.box(df, x='carat', y='price')

In [52]:
df.carat =  pd.cut(df.carat, bins=10, labels=list('abcdefghij'))
df.head()

  carat      cut color clarity  depth  table  price     x     y     z
0     a    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1     a  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2     a     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3     a  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4     a     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [53]:
px.box(df, x='carat', y='price')

In [54]:
df = load_dataset('mpg')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [55]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [56]:
df.origin.value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [57]:
import plotly.express as px

px.histogram(df, x='mpg', nbins=50, title='Histogram MPG')

In [58]:
px.histogram(df, x='mpg', nbins=50, title='Histogram MPG', histnorm='probability density')

In [59]:
px.histogram(df, x='mpg', nbins=50, title='Histogram MPG', histnorm='probability density',
             facet_row='origin', color='origin')

In [60]:
dff = df[(df.origin == 'usa') | (df.origin =='europe')]
px.histogram(dff, x='mpg', color='origin', marginal='violin', title='Rozklad zmiennej mpg(usa vs ue)', opacity=0.7)

In [61]:
px.histogram(df, x='origin')

In [62]:
df = load_dataset('mpg')

In [63]:
import plotly.graph_objects as go

fig = go.Figure(go.Histogram2d(
    x=df.mpg,
    y=df.acceleration,
    colorscale='Viridis',
    nbinsx=30,
    nbinsy=30,
))

fig.add_trace(go.Scatter(
    x=df.mpg,
    y=df.acceleration,
    mode='markers',
    marker={
        'symbol': 'x',
        'opacity': 0.7,
        'color': 'white',
        'size': 8,
        'line': {
            'width': 1
        }
    }))
fig.show()

In [64]:
df = load_dataset('titanic')
df.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [65]:
px.scatter(df, x='age', y='fare', color='survived', facet_col='sex')

In [66]:
px.scatter(df, x='age', y='fare', color='survived', facet_row='sex')

In [67]:
px.scatter(df, x='age', y='fare', color='survived', facet_col='sex', facet_row='pclass',
           category_orders={'pclass': [3,2,1], 'sex': ['female', 'male']})

In [70]:
px.violin(df, x='survived', y='age', color='survived', points='all', box=True)

In [71]:
px.violin(df,  y='age', color='survived',violinmode='overlay')

In [73]:
import yfinance as yf

def fetch_financial_data(company='AMZN'):
  # Using yfinance to fetch financial data as stooq is not implemented
  df = yf.download(company)
  return df

df = fetch_financial_data()
df = df.reset_index()
df.head(2)

/tmp/ipykernel_1506/2475831103.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(company)
[*********************100%***********************]  1 of 1 completed

Price        Date       Close        High         Low        Open    Volume
Ticker                   AMZN        AMZN        AMZN        AMZN      AMZN
0      2026-09-01  254.919998  255.820007  251.929993  254.830002  31700100
1      2026-09-02  254.979996  256.239990  253.399994  254.259995  24013300

In [74]:
df = df[df['Date']>='2019-01-01']
df.describe()

Price,Date,Close,High,Low,Open,Volume
Ticker,,AMZN,AMZN,AMZN,AMZN,AMZN
count,21,21.000000,21.000000,21.000000,21.000000,2.100000e+01
mean,2026-09-15 17:08:34.285714176,252.470952,254.551426,250.095237,252.138334,3.424314e+07
min,2026-09-01 00:00:00,245.960007,247.770004,244.300003,246.020004,2.401330e+07
25%,2026-09-09 00:00:00,249.270004,252.440002,247.179993,248.559998,3.043880e+07
50%,2026-09-16 00:00:00,252.399994,254.690002,250.649994,253.000000,3.305550e+07
75%,2026-09-23 00:00:00,254.979996,257.589996,253.399994,254.830002,3.627540e+07
max,2026-09-30 00:00:00,258.899994,261.119995,256.000000,259.070007,5.227470e+07
std,NaN,4.163493,3.800315,3.763220,3.827324,6.970701e+06

In [75]:
fig = go.Figure(
    go.Ohlc(
        x=df['Date'],
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close']
    )
)
fig.show()

In [76]:
fig = go.Figure(
    go.Candlestick(
        x=df['Date'],
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close']
    )
)
fig.show()

In [78]:
fig = go.Figure(
    go.Waterfall(
        x=['Sprzedaż Stacjonarna', 'sprzedaz Online', 'Przychody', 'Koszty', 'Podatek', 'zysk netto'],
        y=[60,80,0,-50,-30,0],
        measure=['relative', 'relative', 'total', 'relative', 'relative', 'total'],
        text=['+60', '+80', '', '-50', '-30', ''],
        textposition='outside',
        name='Rachunek zystkow i strat 2019'

    )
)
fig.update_layout(
    title='Rachunek zystkow i strat 2019',
    showlegend=True
)
fig.show()

In [81]:
fig = go.Figure(go.Funnel(
    y=['Liczba wyświetlen strony', 'Liczba klikniec', 'liczba nowych rejestracji'],
    x=[3500,500,100],
    textinfo="value+percent initial"
))
fig.show()

In [85]:
fig = go.Figure()
fig.add_trace(go.Funnel(
    y=['Liczba wyświetlen strony', 'Liczba klikniec', 'liczba nowych rejestracji'],
    x=[1000,500,50],
    textinfo="value+percent initial",
    name='reklama 1'
))
fig.add_trace(go.Funnel(
    y=['Liczba wyświetlen strony', 'Liczba klikniec', 'liczba nowych rejestracji'],
    x=[1000,600,40],
    textinfo="value+percent initial",
    name='reklama 2'
))
fig.add_trace(go.Funnel(
    y=['Liczba wyświetlen strony', 'Liczba klikniec', 'liczba nowych rejestracji'],
    x=[2000,900,160],
    textinfo="value+percent initial",
    name='reklama 3'
))
fig.show()

In [88]:
fig = go.Figure(go.Funnelarea(
    labels=['Liczba wyświetlen strony', 'Liczba klikniec', 'liczba nowych rejestracji'],
    values=[2000,500,100]
))
fig.show()

In [89]:
df = pd.read_csv("https://ml-repository-krakers.s3-eu-west-1.amazonaws.com/plotly-course/us-cities-top-1k.csv")
df.head()

         City           State  Population        lat         lon
0  Marysville      Washington       63269  48.051764 -122.177082
1      Perris      California       72326  33.782519 -117.228648
2   Cleveland            Ohio      390113  41.499320  -81.694361
3   Worcester   Massachusetts      182544  42.262593  -71.802293
4    Columbia  South Carolina      133358  34.000710  -81.034814

In [100]:
import plotly.express as px
def plot_map()
  fig = px.scatter_map(df, lat='lat', lon='lon', hover_name='City', hover_data=['State', 'Population'], zoom=3)
  fig.update_layout(margin={'r':10, 't':10, 'l':10, 'b':10})
  fig.show()

In [101]:
df = px.data.gapminder()
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [102]:
df_2007 = df.query('year==2007')
df_2007.describe()

         year     lifeExp           pop     gdpPercap     iso_num
count   142.0  142.000000  1.420000e+02    142.000000  142.000000
mean   2007.0   67.007423  4.402122e+07  11680.071820  425.880282
std       0.0   12.073021  1.476214e+08  12859.937337  249.111541
min    2007.0   39.613000  1.995790e+05    277.551859    4.000000
25%    2007.0   57.160250  4.508034e+06   1624.842248  209.500000
50%    2007.0   71.935500  1.051753e+07   6124.371109  410.000000
75%    2007.0   76.413250  3.121004e+07  18008.835640  636.000000
max    2007.0   82.603000  1.318683e+09  49357.190170  894.000000

In [107]:
px.scatter_geo(df_2007, locations='iso_alpha', color='continent', hover_name='country', size='pop')

In [108]:
px.scatter_geo(df_2007, locations='iso_alpha', color='continent', hover_name='country', size='pop', projection='natural earth')

In [110]:
px.scatter_geo(df, locations='iso_alpha', color='continent', hover_name='country', size='pop', animation_frame='year', projection='natural earth')

In [112]:
px.choropleth(df, locations='iso_alpha', color='lifeExp', hover_name='country')

In [115]:
raw = """AD / Andora
 AE / Zjednoczone Emiraty Arabskie
 AF / Afganistan
 AG / Antigua i Barbuda
 AI / Anguilla
 AL / Albania
 AM / Armenia
 AO / Angola
 AQ / Antarktyda
 AR / Argentyna
 AS / Samoa Amerykańskie
 AT / Austria
 AU / Australia
 AW / Aruba
 AX / Wyspy Alandzkie
 AZ / Azerbejdżan
 BA / Bośnia i Hercegowina
 BB / Barbados
 CL / Chile
 CM / Kamerun
 CN / Chiny
 CO / Kolumbia """

In [124]:
l = raw.split('\n')
l = [row.strip().split('/') for row in l][:-1]
code = []
country = []
for item in l:
  code.append(item[0].strip())
  country.append(item[1].strip())
print(code)
print(country)
df = pd.DataFrame({'code': code, 'country': country})
df = df.reset_index()
df.head()

['AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'CL', 'CM', 'CN']
['Andora', 'Zjednoczone Emiraty Arabskie', 'Afganistan', 'Antigua i Barbuda', 'Anguilla', 'Albania', 'Armenia', 'Angola', 'Antarktyda', 'Argentyna', 'Samoa Amerykańskie', 'Austria', 'Australia', 'Aruba', 'Wyspy Alandzkie', 'Azerbejdżan', 'Bośnia i Hercegowina', 'Barbados', 'Chile', 'Kamerun', 'Chiny']

   index code                       country
0      0   AD                        Andora
1      1   AE  Zjednoczone Emiraty Arabskie
2      2   AF                    Afganistan
3      3   AG             Antigua i Barbuda
4      4   AI                      Anguilla

In [120]:
l

[['AD ', ' Andora'],
 ['AE ', ' Zjednoczone Emiraty Arabskie'],
 ['AF ', ' Afganistan'],
 ['AG ', ' Antigua i Barbuda'],
 ['AI ', ' Anguilla'],
 ['AL ', ' Albania'],
 ['AM ', ' Armenia'],
 ['AO ', ' Angola'],
 ['AQ ', ' Antarktyda'],
 ['AR ', ' Argentyna'],
 ['AS ', ' Samoa Amerykańskie'],
 ['AT ', ' Austria'],
 ['AU ', ' Australia'],
 ['AW ', ' Aruba'],
 ['AX ', ' Wyspy Alandzkie'],
 ['AZ ', ' Azerbejdżan'],
 ['BA ', ' Bośnia i Hercegowina'],
 ['BB ', ' Barbados'],
 ['CL ', ' Chile'],
 ['CM ', ' Kamerun'],
 ['CN ', ' Chiny']]

In [126]:
px.choropleth(df, locations='country', color='index', locationmode='country names', hover_name='country')